// a1.0 Cable Changes This is so ineffiecient its not even funny - Avi 12/30/25
mods.gregtech.packer.recipeBuilder()

// MV Cables
// Removal
// 1x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleCopper')], [fluid('rubber') * 144 * 144])
// 1x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleCopper')], [fluid('silicone_rubber') * 72 * 72])
// 1x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleCopper')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleIron')], [fluid('rubber') * 144 * 144])
// 1x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleIron')], [fluid('silicone_rubber') * 72 * 72])
// 1x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleIron')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleAnnealedCopper')], [fluid('rubber') * 144 * 144])
// 1x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleAnnealedCopper')], [fluid('silicone_rubber') * 72 * 72])
// 1x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleAnnealedCopper')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleCupronickel')], [fluid('rubber') * 144 * 144])
// 1x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleCupronickel')], [fluid('silicone_rubber') * 72 * 72])
// 1x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleCupronickel')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleCopper')], [fluid('rubber') * 144 * 144])
// 2x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleCopper')], [fluid('silicone_rubber') * 72 * 72])
// 2x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleCopper')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleIron')], [fluid('rubber') * 144 * 144])
// 2x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleIron')], [fluid('silicone_rubber') * 72 * 72])
// 2x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleIron')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleAnnealedCopper')], [fluid('rubber') * 144 * 144])
// 2x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleAnnealedCopper')], [fluid('silicone_rubber') * 72 * 72])
// 2x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleAnnealedCopper')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleCupronickel')], [fluid('rubber') * 144 * 144])
// 2x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleCupronickel')], [fluid('silicone_rubber') * 72 * 72])
// 2x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleCupronickel')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 4x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleCopper')], [fluid('rubber') * 288 * 288])
// 4x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleCopper')], [fluid('silicone_rubber') * 144 * 144])
// 4x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleCopper')], [fluid('styrene_butadiene_rubber') * 72 * 72])
// 4x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleIron')], [fluid('rubber') * 288 * 288])
// 4x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleIron')], [fluid('silicone_rubber') * 144 * 144])
// 4x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleIron')], [fluid('styrene_butadiene_rubber') * 72 * 72])
// 4x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleAnnealedCopper')], [fluid('rubber') * 288 * 288])
// 4x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleAnnealedCopper')], [fluid('silicone_rubber') * 144 * 144])
// 4x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleAnnealedCopper')], [fluid('styrene_butadiene_rubber') * 72 * 72])
// 4x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleCupronickel')], [fluid('rubber') * 288 * 288])
// 4x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleCupronickel')], [fluid('silicone_rubber') * 144 * 144])
// 4x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleCupronickel')], [fluid('styrene_butadiene_rubber') * 72 * 72])
// 8x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalCopper')], [fluid('rubber') * 432 * 432])
// 8x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalCopper')], [fluid('silicone_rubber') * 216 * 216])
// 8x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalCopper')], [fluid('styrene_butadiene_rubber') * 108 * 108])
// 8x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalIron')], [fluid('rubber') * 432 * 432])
// 8x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalIron')], [fluid('silicone_rubber') * 216 * 216])
// 8x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalIron')], [fluid('styrene_butadiene_rubber') * 108 * 108])
// 8x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalAnnealedCopper')], [fluid('rubber') * 432 * 432])
// 8x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalAnnealedCopper')], [fluid('silicone_rubber') * 216 * 216])
// 8x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalAnnealedCopper')], [fluid('styrene_butadiene_rubber') * 108 * 108])
// 8x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalCupronickel')], [fluid('rubber') * 432 * 432])
// 8x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalCupronickel')], [fluid('silicone_rubber') * 216 * 216])
// 8x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalCupronickel')], [fluid('styrene_butadiene_rubber') * 108 * 108])
// 16x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexCopper')], [fluid('rubber') * 720 * 720])
// 16x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexCopper')], [fluid('silicone_rubber') * 360 * 360])
// 16x Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexCopper')], [fluid('styrene_butadiene_rubber') * 180 * 180])
// 16x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexIron')], [fluid('rubber') * 720 * 720])
// 16x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexIron')], [fluid('silicone_rubber') * 360 * 360])
// 16x Iron Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexIron')], [fluid('styrene_butadiene_rubber') * 180 * 180])
// 16x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexAnnealedCopper')], [fluid('rubber') * 720 * 720])
// 16x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexAnnealedCopper')], [fluid('silicone_rubber') * 360 * 360])
// 16x Annealed Copper Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexAnnealedCopper')], [fluid('styrene_butadiene_rubber') * 180 * 180])
// 16x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexCupronickel')], [fluid('rubber') * 720 * 720])
// 16x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexCupronickel')], [fluid('silicone_rubber') * 360 * 360])
// 16x Cupronickel Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexCupronickel')], [fluid('styrene_butadiene_rubber') * 180 * 180])
// Addition
mods.gregtech.packer.recipeBuilder()
    .inputs(metaitem('wireGtSingleCopper'), metaitem('foilPolycaprolactam') * 4)
    .outputs(metaitem('cableGtSingleCopper' * 1))
    .duration(100)
    .EUt(7)
    .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleIron'), metaitem('foilPolycaprolactam') * 4)
        .outputs(metaitem('cableGtSingleIron' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleCupronickel'), metaitem('foilPolycaprolactam') * 4)
        .outputs(metaitem('cableGtSingleCupronickel' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleAnnealedCopper'), metaitem('foilPolycaprolactam') * 4)
        .outputs(metaitem('cableGtSingleAnnealedCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleCopper'), metaitem('foilPolycaprolactam') * 6)
        .outputs(metaitem('cableGtDoubleCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleIron'), metaitem('foilPolycaprolactam') * 6)
        .outputs(metaitem('cableGtDoubleIron' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleCupronickel'), metaitem('foilPolycaprolactam') * 6)
        .outputs(metaitem('cableGtDoubleCupronickel' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleAnnealedCopper'), metaitem('foilPolycaprolactam') * 6)
        .outputs(metaitem('cableGtDoubleAnnealedCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleCopper'), metaitem('foilPolycaprolactam') * 8)
        .outputs(metaitem('cableGtQuadrupleCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleIron'), metaitem('foilPolycaprolactam') * 8)
        .outputs(metaitem('cableGtQuadrupleIron' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleCupronickel'), metaitem('foilPolycaprolactam') * 8)
        .outputs(metaitem('cableGtQuadrupleCupronickel' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleAnnealedCopper'), metaitem('foilPolycaprolactam') * 8)
        .outputs(metaitem('cableGtQuadrupleAnnealedCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalCopper'), metaitem('foilPolycaprolactam') * 12)
        .outputs(metaitem('cableGtOctalCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalIron'), metaitem('foilPolycaprolactam') * 12)
        .outputs(metaitem('cableGtOctalIron' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalCupronickel'), metaitem('foilPolycaprolactam') * 12)
        .outputs(metaitem('cableGtOctalCupronickel' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalAnnealedCopper'), metaitem('foilPolycaprolactam') * 12)
        .outputs(metaitem('cableGtOctalAnnealedCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexCopper'), metaitem('foilPolycaprolactam') * 16)
        .outputs(metaitem('cableGtHexCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexIron'), metaitem('foilPolycaprolactam') * 16)
        .outputs(metaitem('cableGtHexIron' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexCupronickel'), metaitem('foilPolycaprolactam') * 16)
        .outputs(metaitem('cableGtHexCupronickel' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexAnnealedCopper'), metaitem('foilPolycaprolactam') * 16)
        .outputs(metaitem('cableGtHexAnnealedCopper' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()

// HV Cables
// Removal
// 1x Gold Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleGold')], [fluid('rubber') * 144 * 144])
// 1x Gold Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleGold')], [fluid('silicone_rubber') * 72 * 72])
// 1x Gold Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleGold')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Silver Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleSilver')], [fluid('rubber') * 144 * 144])
// 1x Silver Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleSilver')], [fluid('silicone_rubber') * 72 * 72])
// 1x Silver Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleSilver')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Electrum Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleElectrum')], [fluid('rubber') * 144 * 144])
// 1x Electrum Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleElectrum')], [fluid('silicone_rubber') * 72 * 72])
// 1x Electrum Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleElectrum')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Kanthal Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleKanthal')], [fluid('rubber') * 144 * 144])
// 1x Kanthal Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleKanthal')], [fluid('silicone_rubber') * 72 * 72])
// 1x Kanthal Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleKanthal')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 1x Blue Alloy Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleBlueAlloy')], [fluid('rubber') * 144 * 144])
// 1x Blue Alloy Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleBlueAlloy')], [fluid('silicone_rubber') * 72 * 72])
// 1x Blue Alloy Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtSingleBlueAlloy')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Gold Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleGold')], [fluid('rubber') * 144 * 144])
// 2x Gold Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleGold')], [fluid('silicone_rubber') * 72 * 72])
// 2x Gold Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleGold')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Silver Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleSilver')], [fluid('rubber') * 144 * 144])
// 2x Silver Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleSilver')], [fluid('silicone_rubber') * 72 * 72])
// 2x Silver Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleSilver')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Electrum Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleElectrum')], [fluid('rubber') * 144 * 144])
// 2x Electrum Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleElectrum')], [fluid('silicone_rubber') * 72 * 72])
// 2x Electrum Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleElectrum')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Kanthal Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleKanthal')], [fluid('rubber') * 144 * 144])
// 2x Kanthal Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleKanthal')], [fluid('silicone_rubber') * 72 * 72])
// 2x Kanthal Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleKanthal')], [fluid('styrene_butadiene_rubber') * 36 * 36])
// 2x Blue Alloy Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleBlueAlloy')], [fluid('rubber') * 144 * 144])
// 2x Blue Alloy Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleBlueAlloy')], [fluid('silicone_rubber') * 72 * 72])
// 2x Blue Alloy Cable * 1
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtDoubleBlueAlloy')], [fluid('styrene_butadiene_rubber') * 36 * 36])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleGold')], [fluid('rubber') * 288 * 288])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleGold')], [fluid('silicone_rubber') * 144 * 144])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleGold')], [fluid('styrene_butadiene_rubber') * 72 * 72])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleSilver')], [fluid('rubber') * 288 * 288])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleSilver')], [fluid('silicone_rubber') * 144 * 144])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleSilver')], [fluid('styrene_butadiene_rubber') * 72 * 72])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleElectrum')], [fluid('rubber') * 288 * 288])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleElectrum')], [fluid('silicone_rubber') * 144 * 144])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleElectrum')], [fluid('styrene_butadiene_rubber') * 72 * 72])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleKanthal')], [fluid('rubber') * 288 * 288])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleKanthal')], [fluid('silicone_rubber') * 144 * 144])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleKanthal')], [fluid('styrene_butadiene_rubber') * 72 * 72])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleBlueAlloy')], [fluid('rubber') * 288 * 288])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleBlueAlloy')], [fluid('silicone_rubber') * 144 * 144])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtQuadrupleBlueAlloy')], [fluid('styrene_butadiene_rubber') * 72 * 72])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalGold')], [fluid('rubber') * 432 * 432])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalGold')], [fluid('silicone_rubber') * 216 * 216])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalGold')], [fluid('styrene_butadiene_rubber') * 108 * 108])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalSilver')], [fluid('rubber') * 432 * 432])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalSilver')], [fluid('silicone_rubber') * 216 * 216])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalSilver')], [fluid('styrene_butadiene_rubber') * 108 * 108])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalElectrum')], [fluid('rubber') * 432 * 432])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalElectrum')], [fluid('silicone_rubber') * 216 * 216])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalElectrum')], [fluid('styrene_butadiene_rubber') * 108 * 108])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalKanthal')], [fluid('rubber') * 432 * 432])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalKanthal')], [fluid('silicone_rubber') * 216 * 216])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalKanthal')], [fluid('styrene_butadiene_rubber') * 108 * 108])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalBlueAlloy')], [fluid('rubber') * 432 * 432])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalBlueAlloy')], [fluid('silicone_rubber') * 216 * 216])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtOctalBlueAlloy')], [fluid('styrene_butadiene_rubber') * 108 * 108])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexGold')], [fluid('rubber') * 720 * 720])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexGold')], [fluid('silicone_rubber') * 360 * 360])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexGold')], [fluid('styrene_butadiene_rubber') * 180 * 180])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexSilver')], [fluid('rubber') * 720 * 720])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexSilver')], [fluid('silicone_rubber') * 360 * 360])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexSilver')], [fluid('styrene_butadiene_rubber') * 180 * 180])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexElectrum')], [fluid('rubber') * 720 * 720])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexElectrum')], [fluid('silicone_rubber') * 360 * 360])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexElectrum')], [fluid('styrene_butadiene_rubber') * 180 * 180])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexKanthal')], [fluid('rubber') * 720 * 720])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexKanthal')], [fluid('silicone_rubber') * 360 * 360])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexKanthal')], [fluid('styrene_butadiene_rubber') * 180 * 180])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexBlueAlloy')], [fluid('rubber') * 720 * 720])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexBlueAlloy')], [fluid('silicone_rubber') * 360 * 360])
mods.gregtech.assembler.removeByInput(7, [metaitem('wireGtHexBlueAlloy')], [fluid('styrene_butadiene_rubber') * 180 * 180])
// Addition
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleGold'), metaitem('foilPlastic') * 4)
        .outputs(metaitem('cableGtSingleGold' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleSilver'), metaitem('foilPlastic') * 4)
        .outputs(metaitem('cableGtSingleSilver' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleElectrum'), metaitem('foilPlastic') * 4)
        .outputs(metaitem('cableGtSingleElectrum' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleKanthal'), metaitem('foilPlastic') * 4)
        .outputs(metaitem('cableGtSingleKanthal' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtSingleBlueAlloy'), metaitem('foilPlastic') * 4)
        .outputs(metaitem('cableGtSingleBlueAlloy' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleGold'), metaitem('foilPlastic') * 6)
        .outputs(metaitem('cableGtDoubleGold' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleSilver'), metaitem('foilPlastic') * 6)
        .outputs(metaitem('cableGtDoubleSilver' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleElectrum'), metaitem('foilPlastic') * 6)
        .outputs(metaitem('cableGtDoubleElectrum' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleKanthal'), metaitem('foilPlastic') * 6)
        .outputs(metaitem('cableGtDoubleKanthal' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtDoubleBlueAlloy'), metaitem('foilPlastic') * 6)
        .outputs(metaitem('cableGtDoubleBlueAlloy' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleGold'), metaitem('foilPlastic') * 8)
        .outputs(metaitem('cableGtQuadrupleGold' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleSilver'), metaitem('foilPlastic') * 8)
        .outputs(metaitem('cableGtQuadrupleSilver' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleElectrum'), metaitem('foilPlastic') * 8)
        .outputs(metaitem('cableGtQuadrupleElectrum' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleKanthal'), metaitem('foilPlastic') * 8)
        .outputs(metaitem('cableGtQuadrupleKanthal' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtQuadrupleBlueAlloy'), metaitem('foilPlastic') * 8)
        .outputs(metaitem('cableGtQuadrupleBlueAlloy' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalGold'), metaitem('foilPlastic') * 12)
        .outputs(metaitem('cableGtOctalGold' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalSilver'), metaitem('foilPlastic') * 12)
        .outputs(metaitem('cableGtOctalSilver' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalElectrum'), metaitem('foilPlastic') * 12)
        .outputs(metaitem('cableGtOctalElectrum' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalKanthal'), metaitem('foilPlastic') * 12)
        .outputs(metaitem('cableGtOctalKanthal' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtOctalBlueAlloy'), metaitem('foilPlastic') * 12)
        .outputs(metaitem('cableGtOctalBlueAlloy' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexGold'), metaitem('foilPlastic') * 16)
        .outputs(metaitem('cableGtHexGold' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexSilver'), metaitem('foilPlastic') * 16)
        .outputs(metaitem('cableGtHexSilver' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexElectrum'), metaitem('foilPlastic') * 16)
        .outputs(metaitem('cableGtHexElectrum' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexKanthal'), metaitem('foilPlastic') * 16)
        .outputs(metaitem('cableGtHexKanthal' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()
mods.gregtech.packer.recipeBuilder()
        .inputs(metaitem('wireGtHexBlueAlloy'), metaitem('foilPlastic') * 16)
        .outputs(metaitem('cableGtHexBlueAlloy' * 1))
        .duration(100)
        .EUt(7)
        .buildAndRegister()