content.createFluid('claymud')
        .setColor(0xAAB3BF)
        .register()

content.createFluid('thickclaymud')
        .setColor(0x451D15)
        .register()

content.createFluid('hotclaymud')
        .setMetalTexture()
        .setViscosity(1300)
        .setColor(0x4A3835)
        .register()

content.createFluid('basicsol1')
        .setColor(0x0203D9)
        .register()
content.createFluid('acidsol1')
        .setColor(0xD4FCF4)
        .register()