content.createFluid('claymud')
        .setColor(0xAAB3BF)
        .register()
content.createFluid('thickclaymud')
        .setColor(0x451D15)
        .register()
content.createFluid('hotclaymud')
        .setMetalTexture()
        .setViscosity(1300)
        .setColor(0x4A3835)
        .register()

content.createFluid('soap')
        .setColor(0xE9BBF2)
        .setMetalTexture()
        .setViscosity(1300)
        .register()

content.createFluid('preciousslurry')
        .setColor(0x1F1506)
        .register()

content.createFluid('fieryblood')
        .setColor(0x781800)
        .register()