content.createItem('foggystone').register()
content.createItem('alkalisalt').register()
content.createItem('yeticlippings').register()
content.createItem('yetiinsulation').register()
content.createItem('philipscatalyst').register()
content.createItem('controlmv').register()

// Custom Casings
content.createBlock('casing_lightsteel')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()

// Components
content.createBlock('component_motorlv')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('component_motormv')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('component_motorhv')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()



content.createBlock('mistyblock')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('twilightblock')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()

content.createBlock('nitroice')
        .setHardness(2.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.GLASS)
        .register()