// Portal Openers
content.createItem('foggystone').register()
content.createItem('levitation_fragment').register()

// Dust Likes
content.createItem('alkalisalt').register()
content.createItem('philipscatalyst').register()
content.createItem('liveroot_dust').register()
content.createItem('dust_chargedcertus').register()
content.createItem('blanchedgold').register()
content.createItem('hydrastone_dust').register()
content.createItem('aeratedendstone_dust').register()


// Processing (Probably Sludges)
content.createItem('crushed_nickelshale').register()

content.createItem('sludge_iron').register()
content.createItem('tungstateshard').register()
content.createItem('sludge_nickel').register()
content.createItem('sludge_bauxite').register()

// Components
content.createItem('laser').register()
content.createItem('motorhv').register()
content.createItem('pistonhv').register()
content.createItem('pumphv').register()
content.createItem('conveyorhv').register()
content.createItem('armhv').register()

// Misc Electronics
content.createItem('controlmv').register()
content.createItem('controlhv').register()
content.createItem('etchedsilicon').register()
content.createItem('inscribedsilicon').register()
content.createItem('yeticlippings').register()
content.createItem('yetiinsulation').register()
content.createItem('blankrune').register()


// Custom Casings
content.createBlock('casing_lightsteel')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('casing_bellowsbottom')
        .setHardness(2.0F)
        .setResistance(2.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('casing_bellows')
        .setHardness(2.0F)
        .setResistance(2.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('casing_bellowstop')
        .setHardness(2.0F)
        .setResistance(2.0F)
        .setSoundType(SoundType.METAL)
        .register()

// Components
content.createBlock('component_motorlv')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('component_motormv')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()
content.createBlock('component_motorhv')
        .setHardness(5.0F)
        .setResistance(10.0F)
        .setSoundType(SoundType.METAL)
        .register()


// Portal Blocks
content.createBlock('mistyblock')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('twilightblock')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('aetherblock')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()

// Stones
content.createBlock('nitroice')
        .setHardness(2.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.GLASS)
        .register()
content.createBlock('hydrastone')
        .setHardness(15.0F)
        .setResistance(5.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('stone_nickelshale')
        .setHardness(5.0F)
        .setResistance(2.0F)
        .setSoundType(SoundType.STONE)
        .register()

// Dimensions
content.createBlock('ow_icon')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('tf_icon')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('nether_icon')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()
content.createBlock('mw_icon')
        .setHardness(1.0F)
        .setResistance(1.0F)
        .setSoundType(SoundType.STONE)
        .register()