// Cutting Machine File
// Made by GTOW Team
import mods.gregtech.recipe.RecipeMap;
val cutter as RecipeMap = <recipemap:cutter>;

// Other Woods
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:4>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:4>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:4>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:5>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:1> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:5>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:1> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:5>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:1> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:6>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:2> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:6>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:2> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:6>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:2> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:7>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:3> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:7>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:3> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_0:7>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:3> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:4>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:4> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:4>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:4> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:4>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:4> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:5>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:5> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:5>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:5> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:5>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:5> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:6>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:6> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:6>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:6> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:6>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:6> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:7>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:7> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:7>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:7> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_1:7>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:7> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:4>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:8> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:4>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:8> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:4>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:8> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:5>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:9> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:5>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:9> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:5>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:9> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:6>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:10> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:6>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:10> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:6>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:10> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:7>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:11> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:7>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:11> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_2:7>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:11> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:4>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:12> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:4>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:12> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:4>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:12> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:5>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:13> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:5>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:13> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:5>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:13> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:6>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:14> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:6>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:14> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:6>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:14> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:7>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<biomesoplenty:planks_0:15> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:7>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<biomesoplenty:planks_0:15> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<biomesoplenty:log_3:7>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<biomesoplenty:planks_0:15> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<rustic:log>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<rustic:planks> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<rustic:log>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<rustic:planks> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<rustic:log>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<rustic:planks> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<rustic:log:1>)
	.fluidInputs(<liquid:water> * 4)
	.outputs(<rustic:planks:1> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(400)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<rustic:log:1>)
	.fluidInputs(<liquid:distilled_water> * 3)
	.outputs(<rustic:planks:1> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(300)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<rustic:log:1>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<rustic:planks:1> * 6, <gregtech:meta_dust:1617> * 2)
	.EUt(7)
	.duration(200)
	.buildAndRegister();

// LV Tier
# Alpha Yeti Clippings
cutter.recipeBuilder()
	.inputs(<twilightforest:alpha_fur>)
	.fluidInputs(<liquid:water> * 100)
	.outputs(<gtow:yeticlippings> * 4)
	.EUt(16)
	.duration(1000)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<twilightforest:alpha_fur>)
	.fluidInputs(<liquid:distilled_water> * 10)
	.outputs(<gtow:yeticlippings> * 4)
	.EUt(12)
	.duration(500)
	.buildAndRegister();
cutter.recipeBuilder()
	.inputs(<twilightforest:alpha_fur>)
	.fluidInputs(<liquid:lubricant> * 1)
	.outputs(<gtow:yeticlippings> * 4)
	.EUt(12)
	.duration(100)
	.buildAndRegister();

// MV Tier