// Controller Recipe




// Wrought Iron Recipes
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_ingot'), item('gregtech:meta_dust', 319))
        .outputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust_tiny', 254))
        .duration(360)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_ingot'), item('gregtech:meta_gem', 319))
        .outputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust_tiny', 254))
        .duration(360)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_ingot'), item('minecraft:coal') * 2)
        .outputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust_tiny', 275))
        .duration(480)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_ingot'), item('gregtech:meta_dust', 266) * 2)
        .outputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust_tiny', 275))
        .duration(480)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_ingot'), item('minecraft:coal:1') * 2)
        .outputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust_tiny', 275))
        .duration(480)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_ingot'), item('gregtech:meta_dust', 271) * 2)
        .outputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust_tiny', 275))
        .duration(480)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_block'), item('gregtech:meta_block_compressed_19', 15))
        .outputs(item('gregtech:meta_block_compressed_20', 15), item('gregtech:meta_dust', 254))
        .duration(1620)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_block'), item('gregtech:meta_block_compressed_16', 10) * 2)
        .outputs(item('gregtech:meta_block_compressed_20', 15), item('gregtech:meta_dust', 275))
        .duration(2160)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('minecraft:iron_block'), item('minecraft:coal_block') * 2)
        .outputs(item('gregtech:meta_block_compressed_20', 15), item('gregtech:meta_dust', 275))
        .duration(2160)
        .EUt(15)
        .buildAndRegister()

// Steel Ingots
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust', 319))
        .outputs(item('gregtech:meta_ingot', 324), item('gregtech:meta_dust_tiny', 254))
        .duration(480)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_gem', 319))
        .outputs(item('gregtech:meta_ingot', 324), item('gregtech:meta_dust_tiny', 254))
        .duration(480)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 335), item('minecraft:coal') * 2)
        .outputs(item('gregtech:meta_ingot', 324), item('gregtech:meta_dust_tiny', 275))
        .duration(640)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust', 266) * 2)
        .outputs(item('gregtech:meta_ingot', 324), item('gregtech:meta_dust_tiny', 275))
        .duration(640)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 335), item('minecraft:coal:1') * 2)
        .outputs(item('gregtech:meta_ingot', 324), item('gregtech:meta_dust_tiny', 275))
        .duration(640)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_ingot', 335), item('gregtech:meta_dust', 271) * 2)
        .outputs(item('gregtech:meta_ingot', 324), item('gregtech:meta_dust_tiny', 275))
        .duration(640)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_block_compressed_20', 15), item('gregtech:meta_block_compressed_19', 15))
        .outputs(item('gregtech:meta_block_compressed_20', 4), item('gregtech:meta_dust', 254))
        .duration(2160)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_block_compressed_20', 15), item('gregtech:meta_block_compressed_16', 10) * 2)
        .outputs(item('gregtech:meta_block_compressed_20', 4), item('gregtech:meta_dust', 275))
        .duration(2880)
        .EUt(15)
        .buildAndRegister()
mods.gregtech.bbbf.recipeBuilder()
        .inputs(item('gregtech:meta_block_compressed_20', 15), item('minecraft:coal_block') * 2)
        .outputs(item('gregtech:meta_block_compressed_20', 4), item('gregtech:meta_dust', 275))
        .duration(2880)
        .EUt(15)
        .buildAndRegister()