// Controller Recipe
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('gtow:controlmv'), item('gregtech:meta_plate', 324) * 16, item('gregtech:meta_item_1', 143) * 2, item('gregtech:fluid_pipe_large', 1012) * 4, item('gregtech:machine', 987))
    .outputs(item('gregtech:machine', 32001))
    .fluidInputs(fluid('soldering_alloy') * 288)
    .duration(1600)
    .EUt(80)
    .buildAndRegister()
mods.gregtech.assembler.recipeBuilder()
        .inputs(item('gtow:controlmv'), item('gregtech:meta_plate', 324) * 16, item('gregtech:meta_item_1', 143) * 2, item('gregtech:fluid_pipe_large', 1012) * 4, item('gregtech:machine', 987))
        .outputs(item('gregtech:machine', 32001))
        .fluidInputs(fluid('tin') * 576)
        .duration(1600)
        .EUt(80)
        .buildAndRegister()




// MV Recipes
// Clay Dust -> Direct Output
mods.gregtech.flottank.recipeBuilder()
        .inputs(item('gregtech:meta_dust', 2063) * 64)
        .fluidInputs(fluid('water') * 8000)
        .outputs(item('gregtech:meta_dust:24017') * 40, item('gregtech:meta_dust:356') * 20)
        .chancedOutput(item('gregtech:meta_dust:24017') * 4, 8000, 500)
        .chancedOutput(item('gregtech:meta_dust:24017') * 4, 8000, 500)
        .chancedOutput(item('gregtech:meta_dust:356') * 4, 8000, 500)
        .fluidOutputs(fluid('thickclaymud') * 500)
        .notConsumable(item('gregtech:meta_item_1', 461).withNbt(['Configuration': 1]))
        .duration(2000)
        .EUt(120)
        .buildAndRegister()
// Clay Dust -> Mud
mods.gregtech.flottank.recipeBuilder()
        .inputs(item('gregtech:meta_dust', 2063) * 64)
        .fluidInputs(fluid('water') * 32000)
        .fluidOutputs(fluid('claymud') * 2000)
        .notConsumable(item('gregtech:meta_item_1', 461).withNbt(['Configuration': 2]))
        .duration(3000)
        .EUt(120)
        .buildAndRegister()

// Water Crushed Ruby -> Chrome
mods.gregtech.flottank.recipeBuilder()
        .inputs(item('gregtech:meta_crushed', 311) * 32)
        .fluidInputs(fluid('water') * 4000)
        .outputs(item('gregtech:meta_crushed_purified', 311) * 32, item('gregtech:meta_dust', 22) * 8)
        .chancedOutput(item('gregtech:meta_dust', 22) * 2, 4000, 1000)
        .chancedOutput(item('gregtech:meta_dust', 24013) * 4, 9000, 400)
        .notConsumable(item('gregtech:meta_item_1', 461).withNbt(['Configuration': 1]))
        .duration(2000)
        .EUt(120)
        .buildAndRegister()
mods.gregtech.flottank.recipeBuilder()
        .inputs(item('gregtech:meta_crushed', 311) * 32)
        .fluidInputs(fluid('distilled_water') * 4000)
        .outputs(item('gregtech:meta_crushed_purified', 311) * 32, item('gregtech:meta_dust', 22) * 8)
        .chancedOutput(item('gregtech:meta_dust', 22) * 2, 8000, 1000)
        .chancedOutput(item('gregtech:meta_dust', 24013) * 4, 9000, 400)
        .notConsumable(item('gregtech:meta_item_1', 461).withNbt(['Configuration': 1]))
        .duration(1500)
        .EUt(120)
        .buildAndRegister()

// HCl Crushed Ruby -> Chrome
mods.gregtech.flottank.recipeBuilder()
        .inputs(item('gregtech:meta_crushed', 311) * 32)
        .fluidInputs(fluid('hydrochloric_acid') * 4000)
        .outputs(item('gregtech:meta_crushed_purified', 311) * 32, item('gregtech:meta_dust', 22) * 16)
        .chancedOutput(item('gregtech:meta_dust', 22) * 8, 9000, 1000)
        .chancedOutput(item('gregtech:meta_dust', 22) * 2, 4000, 1000)
        .chancedOutput(item('gregtech:meta_dust', 24013) * 4, 9000, 400)
        .chancedOutput(item('gregtech:meta_dust', 24013) * 4, 9000, 400)
        .fluidOutputs(fluid('diluted_hydrochloric_acid') * 8000)
        .notConsumable(item('gregtech:meta_item_1', 461).withNbt(['Configuration': 1]))
        .duration(1000)
        .EUt(120)
        .buildAndRegister()